### ISSUE TITLE
linkspector + reviewdog not catching broken links

### ISSUE THREAD

**Issue by brunopgalvao** [UmbrellaDocs/action-linkspector#20]
Hello! 

I have broken links in my [README.md](https://github.com/brunopgalvao/base-parachain/blob/cf079afff7af276625518d27f0da472af01f892e/README.md?plain=1#L21-L23) and the linkspector action does not seem to be catching it.

Here is the workflow:
```yml
name: Linkspector
on: [push]
jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List all files (Debugging)
        run: |
          echo "Listing all files to be scanned:"
          ls -R .
      - name: Run linkspector with reviewdog flags
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check  # You can still specify the reporter here
          fail_on_error: true
          config_file: ".github/workflows/.linkspector.yml"
```
- https://github.com/brunopgalvao/base-parachain/blob/main/.github/workflows/linkchecker.yml

@gaurav-nelson any help here would be appreciated 🙏🏻

**Comment by gaurav-nelson** [comment]
@brunopgalvao Can you share the link for the action run where it didn't catch the broken links?

**Comment by brunopgalvao** [comment]
> @brunopgalvao Can you share the link for the action run where it didn't catch the broken links?

Yes:
- https://github.com/brunopgalvao/base-parachain/actions/runs/10972994309/job/30469879701

There are two broken links in the README.md file:
- https://github.com/brunopgalvao/base-parachain/blob/cf079afff7af276625518d27f0da472af01f892e/README.md?plain=1#L21-L23

I would like for any push to the `main` branch to scan the entire repo for broken links.

**Comment by gaurav-nelson** [comment]
I fixed this issue via https://github.com/UmbrellaDocs/action-linkspector/pull/21 Please wait for new release before you run it again.

The issue was that Linkspector wasn't installing properly becuase of Node version mismatch.

![Screenshot 2024-10-04 at 11 21 30 AM](https://github.com/user-attachments/assets/85a8c4ec-2e0a-4ed1-81b8-38459d88ac65)

**Comment by brunopgalvao** [comment]
Okay. Thanks. What do I have to do on my end? It is still not catching:
- https://github.com/brunopgalvao/base-parachain/actions/runs/11182795973

**Comment by gaurav-nelson** [comment]
I think it is because of your config, when you don't specify `filter_mode` Reviewdog only lists errors for added files. So maybe add `filter-mode: nofilter` and `fail_on_error: true`.

**Comment by brunopgalvao** [comment]
Working!
```
filter_mode: nofilter
fail_on_error: true
```
Thanks a million!
